// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Blog = Collections['blog']['schema']['_output']
export declare const blog: Blog[]

export type Cases = Collections['cases']['schema']['_output']
export declare const cases: Cases[]

export type Legal = Collections['legal']['schema']['_output']
export declare const legal: Legal[]

export type Services = Collections['services']['schema']['_output']
export declare const services: Services[]

export type About = Collections['about']['schema']['_output']
export declare const about: About[]

export type FAQ = Collections['faq']['schema']['_output']
export declare const faq: FAQ[]
